#!/data/data/com.termux/files/usr/bin/bash
if [[ $(id -u) -eq 0 ]]
then
  echo -en "\e[31mE:\e[0m You need to be a common user\n"
  exit 1
else
  echo "Preparing enviroment ..."
  if [[ -d ${PREFIX}/share/applications/xapt ]]
  then
    rm -rf ${PREFIX}/share/applications/xapt
  else
    mkdir -p ${PREFIX}/share/applications 2>/dev/null
  fi
fi
####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
