#!/data/data/com.termux/files/usr/bin/bash
IFS=$'\n\t'
echo "Cloning repository ..."
git clone --quiet https://github.com/ivam3/xapt-management ${PREFIX}/share/applications/xapt
[[ -d ${PREFIX}/share/applications/xapt ]] && {
  echo "Installing requirements ..."
  for i in manifiest.json postinst postrm preinst prerm xapt-installer;do rm $i;done
  chmod 751 -R ${PREFIX}/share/applications/xapt
  python -m pip --no-color --quiet --no-cache-dir install -r ${PREFIX}/share/applications/xapt/requirements.txt
} || {
  echo -en "\e[31mE:\e[0m xapt-management directory missing ... \e[33mAborting.\e[0m\n";
  exit 1;
}
exit 0
####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
